### ISSUE TITLE
欢迎弹窗能否只显示一次

### ISSUE THREAD

**Issue by 9WiSHao** [SEhzm/sb6657#2]
就是那个欢迎来自xx的朋友弹窗
目前回一次首页就弹一次，有点影响使用，希望改成只在首次进入网站弹，单纯切换tab不弹

**Comment by 9WiSHao** [comment]
【重现步骤】：

1、切换至其他tab（如全部烂梗）
2、点击切换回首页tab

【实际结果】：

欢迎弹窗会重复出现
![image](https://github.com/user-attachments/assets/9e77c6c5-eb0a-4d32-bb90-cae0fe4c94df)

【预期结果】：

只在第一次进入首页tab 或者第一次进入网站出现此弹窗

**Comment by SEhzm** [comment]
好的
