### ISSUE TITLE
网站进入后无法获得超级大爆

### ISSUE THREAD

**Issue by singed1117** [SEhzm/sb6657#4]
![image](https://github.com/user-attachments/assets/97399983-f94a-4425-a076-5949c9d757f9)
一直转圈圈进不去，快点维护 我要看刘氏家族烂梗

**Comment by SEhzm** [comment]
你是不是在国外

**Comment by yes-zhang** [comment]
为什么国外不同的ip段 有的能加载出来烂梗 有的不行 网页其他元素都能加载 国内国外是谁屏蔽了谁

**Comment by SEhzm** [comment]
> 为什么国外不同的ip段 有的能加载出来烂梗 有的不行 网页其他元素都能加载 国内国外是谁屏蔽了谁

网页的服务器在国外，加载烂梗的服务器在国内，所以加载烂梗可能较慢，加载不出来可能是因为加载超时了，你可以尝试加速国内的vpn

**Comment by yes-zhang** [comment]
好的好的 祝网页大爆
